name: Add Comment to New Issues
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Comment
        run: |
          COMMENT="Created by Human"
          ISSUE_NUMBER=$(jq -r ".issue.number" $GITHUB_EVENT_PATH)
          
          # Use secrets.GITHUB_TOKEN for authentication
          curl -X POST "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$COMMENT\"}"
